// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxzsohovjjmuofxbkysh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4enNvaG92amptdW9meGJreXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTc0MzMsImV4cCI6MjA2NDk5MzQzM30.wZUXu7lKMdy6yz3Y_IJEQ4PTv85Tc1HvLMefXOmW6ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);